import React from 'react';

export default function TransactionPreview({ batch }) {
    if (!batch) return null;
  return (
    <div className="border p-3 mb-3" style={{ minWidth: 700 }}>
      <div className="d-flex justify-content-between align-items-start">
        <div>
          <h5 className="mb-1">Batch Transaction Details</h5>
          <div className="small text-muted">Generated by: {batch.createdBy}</div>
          <div className="small text-muted">Created on: {new Date(batch.createdAt).toLocaleString()}</div>
        </div>
        <div className="text-end small">
          <div className="fw-bold">Status: {batch.status}</div>
          <div>Reference: {batch.batchReference}</div>
        </div>
      </div>
      <hr />
      <h6>Batch Summary</h6>
      <p className="small mb-1">Total Payments: {batch.transactions?.length || 0}</p>
      <p className="small mb-1">Total Amount: {batch.currency} {batch.totalDebitAmount}</p>
      <table className="table table-sm table-bordered mt-2">
        <thead className="table-light">
          <tr>
            <th>Beneficiary</th>
            <th>Account No</th>
            <th>Salary ({batch.currency})</th>
          </tr>
        </thead>
        <tbody>
          {batch.transactions?.map((tx) => (
            <tr key={tx.id}>
        <td>{tx.employeeName}</td>
 <td>{tx.employeeAccountNo}</td>
              <td>{tx.amount}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
